### ISSUE TITLE
Updating wkhtmltopdf scales down font-sizes

### ISSUE THREAD

**Issue by th122** [UB-Mannheim/ape#14]
**Note:** This is only relevant for updating older installations

**Issue:** The release change from wkhtmltopdf 0.12.3 to 0.12.4 changed handling of different screen-resolutions. This led to a number of size issues, documented in wkhtmltopdf/wkhtmltopdf#3241. The fix, release 0.12.5 still renders fonts smaller than 0.12.3 did. Especially for hold shelf slips our staff very much wanted to keep the previous size.

**Fix:**  Adding the parameter `--disable-smart-shrinking` in the 0.12.5 production chain resulted in printouts matching their counterpart from the system running 0.12.3

For sites starting out with  0.12.5 this would probably not be necessary since they would start their design process with the scaling as-is.

**Comment by mahaesin** [comment]
We now use [weasyprint](https://github.com/Kozea/WeasyPrint) for creation of PDF-files.

**Comment by myselfhimself** [comment]
@mahaesin Hello, considering weasyprint too and did some tests. From wkhtmltopdf to weasyprint, for generating an A4 PDF (with `@page { size: 210mm 297mm; }`) the fonts appear much bigger, would you have a simple tip for switching? Did you have to rewrite many CSS rules?

**Comment by mahaesin** [comment]
Luckily our templates/input files already specified absolute font sizes (for paragraphs, headings, tds) in "cm" or "em" so when we began to evaluate weasyprint the PDFs looked roughly the same.
Basically only page borders, and margins/padding of headings and table cells needed to be corrected.

Using the file weasy.css to globally override CSS formatting we only had 4-5 classes and ids that needed changes.
```
@page { 
    margin-top: 0.5cm; 
    margin-left: 1.1cm; 
    margin-right: 1.2cm; 
    margin-bottom: 0.5cm
}
#someId th, td {
    padding-top: 0.2em;
    padding-bottom: 0.2em;
}
#someId h1 {
    margin-top: 0;
    margin-bottom: 0;
    padding-top: 0.2em;
    padding-bottom: 0.2em;
}
.myclass {
    line-height: 4.5;
}
...

```
In the next step we changed our templates so we could remove this overrides.


Perhaps it will be enough to overwrite font-size for body and headings?

```
body, p {
  font-size: 1em;
}

h1 {
  font-size: 2.5em;
}
...
```

**Comment by myselfhimself** [comment]
Hello @mahaesin thank you for your insightful notes! We had just two documents to migrate, working in 'px' though.. and ended up tuning the styles a bit like you obviously, yesterday. Thanks for sharing!
