### ISSUE TITLE
Wkhtmltopdf Fonts

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/ape#8]
Is it possible to add additional fonts like Chinese? At the moment non contained fonts cannot be printed, fields are emtpy in pdf.

**Comment by th122** [comment]
To illustrate the difference, here's a Resource Request Slip including the Kanji representation of a title  

- converted by printing to pdf on MacOS X: [Magazinzettel Japanologie Demo - Dokumentation.pdf](https://github.com/UB-Mannheim/ape/files/796031/Magazinzettel.Japanologie.Demo.-.Dokumentation.pdf)
- converted by wkhtmltopdf, leaving all the Kanji blank: [Japanologie DE-11-001973001 - wkhtml2pdf.pdf](https://github.com/UB-Mannheim/ape/files/796035/Japanologie.DE-11-001973001.-.wkhtml2pdf.pdf)
- and the html source text to generate the Resource Request Slip (rename to html after download):
[Magazinzettel__AsA-JP____DE-11-001973001.txt](https://github.com/UB-Mannheim/ape/files/796080/Magazinzettel__AsA-JP____DE-11-001973001.txt)

Tatjana Heuser (Universitätsbibliothek der Humboldt-Universität zu Berlin)
